name: "publish"

on:
    push:
        branches: ["trunk"]
        tags-ignore: ["**"]
    pull_request:
    release:
      types: [published]

jobs:
    call-publish:
        uses: "nayrid/.github/.github/workflows/shared-publish.yaml@trunk"
        secrets: inherit
